name: Tests

#runs when:
on:
  #any branch is pushed
  push:
    branches:
      - '*'
  #any pull request is made on a main branch
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.8", "3.9", "3.10"]
        steps:
          # Basic checkouts & setup
          - name: Check out repository
            uses: actions/checkout@v3
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v3
            with:
              python-version: ${{ matrix.python-version }}

          # Run pytest
          - name: Pytest
            run: |
              export PYTHONPATH=$(pwd)
              pytest test/ -v

            # Run pylint
          - name: Install pylint
            run: |
              python -m pip install --upgrade pip
              pip install pylint           
          - name: Pylint
            run: |
              export PYTHONPATH=$(pwd)
              pylint $(git ls-files '*.py' | grep -v 'test/') --disable=C0103